---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qmm-g-Excellent/Configs.git
          search-paths:
            - "station*"
security:
  basic:
    enabled: true
  user:
    name: qmm
    password: 123



